sudo: false
language: python
python:
  - "2.7"
node_js:
  - "0.10"
env:
  global:
    - PIP_DOWNLOAD_CACHE="pip_cache"
branches:
  only:
    - master
cache:
  directories:
    - pip_cache
before_script:
  - flake8 bedrock lib
  - python manage.py runscript check_calendars
  - mysql -e 'create database bedrock_test;'
  - python manage.py version
  - python manage.py syncdb --noinput --migrate
  - python manage.py collectstatic --noinput -v 0
  - python manage.py update_product_details
  - svn checkout https://svn.mozilla.org/projects/mozilla.com/trunk/locales/ locale
  - npm install -g casperjs@1.1.0-beta3
  - phantomjs --version
  - casperjs --version
script:
  - coverage run manage.py test
  - casperjs test tests/functional --domain=https://www-dev.allizom.org --config=tests/config.json
before_install:
  - git submodule update --init --recursive
install:
  - python bin/peep.py install -r requirements/dev.txt --no-use-wheel
  - python bin/peep.py install -r requirements/prod.txt --no-use-wheel
after_success:
  - pip install coveralls
  - coveralls
notifications:
  irc:
    channels:
      - "irc.mozilla.org#www"
    on_success: change
    on_failure: always
    use_notice: true
